// Dane sklepu: skiny, trails (flagi), kolory i fasony czapek, odcienie skory, zarost.
// Ceny musza sie zgadzac z tabela shop_prices w Supabase (supabase-anticheat-v2.sql).
// Klasyczny skrypt (nie modul) - stale sa globalne i widoczne w main.js.
const SKINS = [
  { id:'classic', name:'Klasyczny', price:0,  colors:{hat:'#d13b2b', shirt:'#d13b2b', overalls:'#274bc4', skin:'#f6b17a'} },
  { id:'luigi',   name:'Zielony Sanitariusz', price:15, colors:{hat:'#2e9e4a', shirt:'#2e9e4a', overalls:'#274bc4', skin:'#f6b17a'} },
  { id:'wario',   name:'Chciwiec', price:25, colors:{hat:'#e4c02e', shirt:'#e4c02e', overalls:'#6a2ea0', skin:'#f6b17a'} },
  { id:'fire',    name:'Ognisty', price:35, colors:{hat:'#f4f4f4', shirt:'#f4f4f4', overalls:'#d13b2b', skin:'#f6b17a'} },
  { id:'ice',     name:'Lodowy', price:40, colors:{hat:'#bfe9ff', shirt:'#bfe9ff', overalls:'#2e86c9', skin:'#f6b17a'} },
  { id:'ninja',   name:'Ninja', price:45, colors:{hat:'#1a1a2e', shirt:'#1a1a2e', overalls:'#3a1030', skin:'#e0a86e'} },
  { id:'pirate',  name:'Pirat', price:55, colors:{hat:'#3a2a1a', shirt:'#4a4a4a', overalls:'#7a1414', skin:'#e0a86e'} },
  { id:'shadow',  name:'Cień', price:50, colors:{hat:'#2b2b2b', shirt:'#2b2b2b', overalls:'#111111', skin:'#c98f5e'} },
  { id:'robot',   name:'Robot', price:60, colors:{hat:'#9aa5b1', shirt:'#c7d0d8', overalls:'#5a6570', skin:'#d8dee3'} },
  { id:'zombie',  name:'Zombie', price:60, colors:{hat:'#4a5a2e', shirt:'#5a6e34', overalls:'#2e3a1a', skin:'#7ba05b'} },
  { id:'royal',   name:'Królewski', price:70, colors:{hat:'#5b2e9e', shirt:'#5b2e9e', overalls:'#2a1050', skin:'#f6b17a'} },
  { id:'neon',    name:'Neonowy', price:75, colors:{hat:'#ff2e9e', shirt:'#ff2e9e', overalls:'#00e5c7', skin:'#f6b17a'} },
  { id:'gold',    name:'Złoty VIP', price:80, colors:{hat:'#ffd23f', shirt:'#ffd23f', overalls:'#b8860b', skin:'#f6b17a'} },
  { id:'cosmic',  name:'Kosmiczny', price:100, colors:{hat:'#1a1440', shirt:'#2e2870', overalls:'#0a0820', skin:'#c9b8ff'} },
  { id:'warrior', name:'Wojownik', price:90, colors:{hat:'#8a1a1a', shirt:'#9a9aa0', overalls:'#5a1010', skin:'#e0a86e'} },
  { id:'forest',  name:'Leśny', price:85, colors:{hat:'#3a5a2e', shirt:'#5a6e3e', overalls:'#4a3620', skin:'#e0a86e'} },
  { id:'vampire', name:'Wampir', price:95, colors:{hat:'#1a0e14', shirt:'#3a0a14', overalls:'#0e0a12', skin:'#d8c8d8'} },
  { id:'beach',   name:'Plażowy', price:65, colors:{hat:'#ff8a3d', shirt:'#ffd23f', overalls:'#2e86c9', skin:'#e0a86e'} },
  { id:'diamond', name:'Diamentowy', price:120, colors:{hat:'#bfeaff', shirt:'#8fdcf5', overalls:'#2ea8c9', skin:'#f6b17a'} },
  { id:'samurai', name:'Samuraj', price:105, colors:{hat:'#8a1a2a', shirt:'#1a1a1a', overalls:'#3a1a1a', skin:'#e0a86e'} },
  { id:'toxic',   name:'Toksyczny', price:80, colors:{hat:'#9aff3d', shirt:'#5aab1a', overalls:'#1a3a0a', skin:'#8fd944'} },
  { id:'pharaoh', name:'Faraon', price:110, colors:{hat:'#ffd23f', shirt:'#1e5aa8', overalls:'#0a2a5a', skin:'#c9946a'} },
  { id:'candy',   name:'Cukierkowy', price:70, colors:{hat:'#ff6fa5', shirt:'#ffb3d1', overalls:'#7a3ac9', skin:'#f6b17a'} },
  { id:'steampunk', name:'Steampunk', price:115, colors:{hat:'#a86a2e', shirt:'#5a3a1a', overalls:'#2e1a0a', skin:'#e0a86e'} },
];

const TRAILS = [
  { id:'none',        name:'Brak',        price:0,  colors:['transparent'] },
  { id:'ukraine',     name:'Ukraina',     price:40, colors:['#0057b7','#ffd700'] },
  { id:'poland',      name:'Polska',      price:40, colors:['#ffffff','#dc143c'] },
  { id:'lithuania',   name:'Litwa',       price:40, colors:['#fdb913','#006a44','#c1272d'] },
  { id:'latvia',      name:'Łotwa',       price:40, colors:['#9e3039','#ffffff','#9e3039'] },
  { id:'germany',     name:'Niemcy',      price:45, colors:['#000000','#dd0000','#ffce00'] },
  { id:'italy',       name:'Włochy',      price:45, colors:['#009246','#ffffff','#ce2b37'] },
  { id:'sweden',      name:'Szwecja',     price:45, colors:['#006aa7','#fecc02'] },
  { id:'japan',       name:'Japonia',     price:50, colors:['#ffffff','#bc002d'] },
  { id:'usa',         name:'USA',         price:50, colors:['#3c3b6e','#ffffff','#b22234'] },
  { id:'france',      name:'Francja',     price:45, colors:['#0055a4','#ffffff','#ef4135'] },
  { id:'spain',       name:'Hiszpania',   price:45, colors:['#aa151b','#f1bf00'] },
  { id:'netherlands', name:'Holandia',    price:40, colors:['#ae1c28','#ffffff','#21468b'] },
  { id:'belgium',     name:'Belgia',      price:40, colors:['#000000','#fae042','#ed2939'] },
  { id:'austria',     name:'Austria',     price:40, colors:['#ed2939','#ffffff','#ed2939'] },
  { id:'ireland',     name:'Irlandia',    price:40, colors:['#169b62','#ffffff','#ff883e'] },
  { id:'finland',     name:'Finlandia',   price:45, colors:['#ffffff','#003580'] },
  { id:'norway',      name:'Norwegia',    price:45, colors:['#ba0c2f','#ffffff','#00205b'] },
  { id:'denmark',     name:'Dania',       price:40, colors:['#c60c30','#ffffff'] },
  { id:'iceland',     name:'Islandia',    price:45, colors:['#02529c','#ffffff','#dc1e35'] },
  { id:'switzerland', name:'Szwajcaria',  price:45, colors:['#d52b1e','#ffffff'] },
  { id:'czechia',     name:'Czechy',      price:40, colors:['#ffffff','#d7141a','#11457e'] },
  { id:'uk',          name:'Wielka Brytania', price:55, colors:['#012169','#ffffff','#c8102e'] },
  { id:'canada',      name:'Kanada',      price:50, colors:['#d52b1e','#ffffff'] },
  { id:'greece',      name:'Grecja',      price:45, colors:['#0d5eaf','#ffffff'] },
  { id:'portugal',    name:'Portugalia',  price:45, colors:['#006600','#ff0000','#ffe000'] },
  { id:'hungary',     name:'Węgry',       price:40, colors:['#cd2a3e','#ffffff','#436f4d'] },
  { id:'romania',     name:'Rumunia',     price:40, colors:['#002b7f','#fcd116','#ce1126'] },
  { id:'estonia',     name:'Estonia',     price:40, colors:['#0072ce','#000000','#ffffff'] },
  { id:'bulgaria',    name:'Bułgaria',    price:40, colors:['#ffffff','#00966e','#d62612'] },
  { id:'turkey',      name:'Turcja',      price:50, colors:['#e30a17','#ffffff'] },
  { id:'brazil',      name:'Brazylia',    price:50, colors:['#009c3b','#ffdf00','#002776'] },
  { id:'pirate',      name:'Piracka flaga', price:60, colors:['#111111','#f2f2f2'] },
];

const HATS = [
  { id:'default', name:'Domyślna', price:0,  color:null },
  { id:'red',     name:'Czerwona', price:20, color:'#d13b2b' },
  { id:'blue',    name:'Niebieska', price:20, color:'#2e6bd6' },
  { id:'green',   name:'Zielona',  price:20, color:'#2e9e4a' },
  { id:'purple',  name:'Fioletowa', price:25, color:'#7a3ac9' },
  { id:'black',   name:'Czarna',   price:25, color:'#1a1a1a' },
  { id:'pink',    name:'Różowa',   price:25, color:'#ff6fa5' },
  { id:'gold',    name:'Złota',    price:40, color:'#ffd23f' },
  { id:'orange',  name:'Pomarańczowa', price:25, color:'#ff8a2b' },
  { id:'teal',    name:'Turkusowa', price:25, color:'#1fb5ad' },
  { id:'white',   name:'Biała',    price:25, color:'#f2f2f2' },
  { id:'maroon',  name:'Bordowa',  price:25, color:'#7a1f2b' },
  { id:'lime',    name:'Limonkowa', price:25, color:'#a6e22e' },
  { id:'navy',    name:'Granatowa', price:25, color:'#1c2f6b' },
  { id:'brown',   name:'Brązowa',  price:20, color:'#8a5a2b' },
  { id:'silver',  name:'Srebrna',  price:40, color:'#c0c6d0' },
  { id:'sky',      name:'Błękitna',    price:25, color:'#5ec8ff' },
  { id:'mint',     name:'Miętowa',     price:25, color:'#7ee8c3' },
  { id:'coral',    name:'Koralowa',    price:25, color:'#ff6f61' },
  { id:'yellow',   name:'Żółta',       price:25, color:'#ffe94a' },
  { id:'magenta',  name:'Magenta',     price:30, color:'#e0219a' },
  { id:'olive',    name:'Oliwkowa',    price:20, color:'#7a8b2e' },
  { id:'indigo',   name:'Indygo',      price:30, color:'#4b3bbf' },
  { id:'lavender', name:'Lawendowa',   price:25, color:'#b79cff' },
  { id:'peach',    name:'Brzoskwiniowa', price:25, color:'#ffb98a' },
  { id:'slate',    name:'Łupkowa',     price:20, color:'#5d6b7a' },
  { id:'forest',   name:'Leśna',       price:25, color:'#1e6b3a' },
  { id:'khaki',    name:'Khaki',       price:20, color:'#b5a26a' },
  { id:'cyan',     name:'Cyjan',       price:30, color:'#00c2d1' },
  { id:'copper',   name:'Miedziana',   price:35, color:'#b86b3c' },
];

// fasony czapek (ksztalt); kolor czapki wybiera sie osobno w HATS
const HAT_STYLES = [
  { id:'cap',      name:'Czapka z daszkiem',   price:0 },
  { id:'beanie',   name:'Czapka zimowa',       price:25 },
  { id:'helmet',   name:'Hełm',                price:30 },
  { id:'headband', name:'Opaska ninja',        price:30 },
  { id:'cowboy',   name:'Kapelusz kowbojski',  price:40 },
  { id:'tophat',   name:'Cylinder',            price:45 },
  { id:'wizard',   name:'Kapelusz czarodzieja', price:50 },
  { id:'crown',    name:'Korona',              price:80 },
  { id:'flatcap',   name:'Kaszkiet',              price:25 },
  { id:'bucket',    name:'Kapelusz wędkarza',     price:25 },
  { id:'beret',     name:'Beret',                 price:30 },
  { id:'party',     name:'Czapeczka urodzinowa',  price:30 },
  { id:'propeller', name:'Czapka ze śmigłem',     price:35 },
  { id:'catears',   name:'Kocie uszy',            price:35 },
  { id:'fez',       name:'Fez',                   price:35 },
  { id:'santa',     name:'Czapka Mikołaja',       price:40 },
  { id:'chef',      name:'Czapka kucharska',      price:40 },
  { id:'pirate',    name:'Kapelusz pirata',       price:50 },
  { id:'sombrero',  name:'Sombrero',              price:55 },
  { id:'viking',    name:'Hełm wikinga',          price:60 },
];

const SKIN_TONES = [
  { id:'default', name:'Domyślna', price:0,  color:null },
  { id:'light',   name:'Jasna',    price:15, color:'#f6c8a0' },
  { id:'tan',     name:'Śniada',   price:15, color:'#e0a86e' },
  { id:'dark',    name:'Ciemna',   price:15, color:'#a8703e' },
  { id:'pale',    name:'Blada',    price:15, color:'#e8d8c8' },
  { id:'alien',   name:'Zielona (kosmita)', price:30, color:'#8fd944' },
  { id:'blue',    name:'Niebieska', price:30, color:'#8fc7ff' },
  { id:'deep',    name:'Bardzo ciemna', price:15, color:'#6b4226' },
  { id:'olive',   name:'Oliwkowa', price:15, color:'#c9a67a' },
  { id:'pink',    name:'Różowa',   price:25, color:'#ffb3c7' },
  { id:'purple',  name:'Fioletowa', price:30, color:'#b58cf0' },
  { id:'gold',    name:'Złota',    price:40, color:'#f7d774' },
  { id:'gray',    name:'Szara',    price:25, color:'#b8bcc6' },
  { id:'orange',  name:'Pomarańczowa', price:30, color:'#ff9f43' },
  { id:'red',     name:'Czerwona', price:30, color:'#e4573d' },
  { id:'porcelain', name:'Porcelanowa', price:15, color:'#f7e1d0' },
  { id:'sand',      name:'Piaskowa',    price:15, color:'#e8c9a0' },
  { id:'honey',     name:'Miodowa',     price:15, color:'#d9a066' },
  { id:'caramel',   name:'Karmelowa',   price:15, color:'#b97a4b' },
  { id:'mocha',     name:'Mokka',       price:15, color:'#8a5a3c' },
  { id:'ebony',     name:'Heban',       price:20, color:'#4a2c1a' },
  { id:'mint',      name:'Miętowa',     price:25, color:'#9be8c9' },
  { id:'yellow',    name:'Żółta',       price:25, color:'#ffe066' },
  { id:'teal',      name:'Turkusowa',   price:30, color:'#4fd1c5' },
  { id:'lavender',  name:'Lawendowa',   price:25, color:'#cbb8ff' },
  { id:'lime',      name:'Limonkowa',   price:30, color:'#b6e34a' },
  { id:'white',     name:'Biała',       price:35, color:'#f5f5f5' },
  { id:'black',     name:'Czarna',      price:35, color:'#2b2b33' },
  { id:'magenta',   name:'Magenta',     price:30, color:'#e070c0' },
];

const FACIAL_HAIR = [
  { id:'mustache', name:'Wąsy (domyślne)', price:0 },
  { id:'none',     name:'Gładko ogolony', price:10 },
  { id:'beard',    name:'Broda', price:20 },
  { id:'goatee',   name:'Kozia bródka', price:20 },
  { id:'pencil',    name:'Cienkie wąsy',      price:15 },
  { id:'stubble',   name:'Zarost 3-dniowy',   price:15 },
  { id:'sideburns', name:'Baki',              price:20 },
  { id:'handlebar', name:'Wąsy kręcone',      price:25 },
  { id:'walrus',    name:'Wąsy morsa',        price:25 },
  { id:'vandyke',   name:'Van Dyke',          price:30 },
  { id:'fullbeard', name:'Długa broda',       price:35 },
  { id:'santa',     name:'Broda Mikołaja',    price:45 },
];
